### ISSUE TITLE
Support HTTP CONNECT method bootstrap

### ISSUE THREAD

**Issue by DanGould** [payjoin/ohttp-relay#14]
The Oblivious HTTP specification requires clients obtain ohttp-keys from the OHTTP Gateway but leaves a mechanism for doing so explicitly unspecified.

I have been [working on HTTPS-in-WebSocket](https://github.com/payjoin/ohttp-relay/pull/11) As a mechanism to do this from web environments (mutiny, bitmask) [where HTTP CONNECT is not available](https://security.stackexchange.com/questions/203396/whats-the-security-concern-of-browsers-using-the-http-connect-method/203421#203421).

The simplest way to do this in an authenticated way is to use HTTP CONNECT to tunnel HTTPS-in-HTTPS from client to relay to gateway. We should support a second bootstrap method with its own feature that listens for CONNECT method requests and forwards them to the OHTTP_GATEWAY. Such requests must be HTTPS requests between client and gateway in order to ensure authentication.

@oleonardolima this might interest you

**Comment by oleonardolima** [comment]
Cool, thanks! I'll take a look at it.
